name: ElasticWorlkflow
on:
  workflow_dispatch:
jobs:
  run-demo-app:
    runs-on: aws_runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python 3.10.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.6'
    - name: Run script that echo outputs
      run: python main.py
